### ISSUE TITLE
Release v2.3 ships with docker-compose.yml using images that are no longer available

### ISSUE THREAD

**Issue by cweickhmann** [OpenSlides/openslides-docker#11]
Hi again,

I've painfully recognised that a bunch of images used in v2.3 release are no longer available, hence build fails:
`os-core`, `os-web` and `os-worker` are no longer available.

The current commit's docker-compose.yml is updated accordingly. There should hence soon be a new release. Pretty please :-)

**Comment by emanuelschuetze** [comment]
Please use https://github.com/OpenSlides/openslides-docker-compose which is updated for OpenSlides 3.0/master.
