### ISSUE TITLE
Docker-compose build fails at 21/33 in server for compose-big-mode

### ISSUE THREAD

**Issue by cweickhmann** [OpenSlides/openslides-docker#8]
I've run into several build errors with openslides-docker. The following happened recently:
In compose-big-mode i run
```bash
docker-compose build
```
which seems to run fine but then fails at step 21 of 33 (I guess when it's executing the server/Dockerfile) with the error
```bash
Step 21/33 : RUN ng config -g cli.warnings.versionMismatch false &&   cd client &&   npm install
 ---> Running in 67709f33aee9
/bin/sh: 1: cd: can't cd to client
ERROR: Service 'server' failed to build: The command '/bin/sh -c ng config -g cli.warnings.versionMismatch false &&   cd client &&   npm install' returned a non-zero code: 2
```

I first thought this was a wrong line ending, but it turns out not to be.

It seems to be related with the commit of OpenSlides/OpenSlides@70437ed referenced in the docker-compose.yml . Changing the hash there to e.g. the current one (OpenSlides/OpenSlides@211a0b8ebb9f51ac29717063b2bf3045249c2d2a) solves the issue.

REQUEST:
Please check that docker-compose.yml actually builds before committing it.

Commits:
openslides-docker: a32ac45
OpenSlides/OpenSlides@70437ed

**Comment by jsaalfeld** [comment]
Seems that I have forgotten to commit the `README` and `docker-compose.yml` as i fixed the `sed`-commands to the new `settings.tpl`. Sorry for the inconvenience. I've rebuild and tested it with the commit https://github.com/OpenSlides/openslides-docker/commit/2b284625e1f83d5a349e1c84a472c46475943614

Thank you for reporting!
